server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri:lb://empleado-service
          predicates:
            - Path=/empleados/**
        - id: horasextra-service
          uri: lb://horaextra-service
          predicates:
            - Path=/hora-extra/**
        - id: justificacion-service
          uri: lb://justificacion-service
          predicates:
            - Path=/justificacion/**
        - id: rrhh-service
          uri: lb://rrhh-service
          predicates:
            - Path=/rrhh/** 
        - id: upload-service
          uri: lb://upload-service
          predicates:
            - Path=/upload/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}