server:
  port: 8090 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone:  ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: http://localhost:8001
          predicates:
            - Path=/empleados/**
        - id: horasextra-service
          uri: http://localhost:8002
          predicates:
            - Path=/hora-extra/**
        - id: justificacion-service
          uri: http://localhost:8003
          predicates:
            - Path=/justificacion/**
        - id: rrhh-service
          uri: http://localhost:8004
          predicates:
            - Path=/rrhh/** 
        - id: upload-service
          uri: http://localhost:8005
          predicates:
            - Path=/upload/**